name: simple_mysql_orm
version: 6.3.1
description: A simple ORM wrapper for mysql with Transaction support.
repository: https://github.com/bsutton/simple_mysql_orm
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  args: ^2.3.1
  collection: ^1.15.0
  date_time: ^0.12.0
  dcli: ^8.2.0
  intl: ^0.20.2
  logging: ^1.0.2
  meta: ^1.7.0
  money2: ^6.0.5
  mysql_client: ^0.0.27
  path: ^1.8.3
  recase: ^4.0.0
  scope: ^5.1.0
  settings_yaml: ^8.1.0
dev_dependencies:
  lint_hard: ^6.2.1
  test: ^1.19.5
executables:
  build_dao:
